/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Anaclita
 */
public class CashierDashboard extends javax.swing.JFrame {

    /**
     * Creates new form AdminDashboard
     */
    Color DefaultColor, ClickedColor;

    public CashierDashboard(String name) {
        initComponents();
        labelCashierName2.setText(name);
        mainPane.add(new AdminDashboardPanel()).setVisible(true);

        this.setVisible(true);
        this.setLocationRelativeTo(null);

        DefaultColor = new Color(25, 118, 211);
        ClickedColor = new Color(255, 255, 255);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        DashName = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        labelCashierName2 = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        labelCashierName = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Order = new javax.swing.JPanel();
        ordersLabel = new javax.swing.JLabel();
        Customer = new javax.swing.JPanel();
        customerLabel = new javax.swing.JLabel();
        mainPane = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(25, 118, 211));

        DashName.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        DashName.setForeground(new java.awt.Color(255, 255, 255));
        DashName.setText("Nackingspol Water Refilling Station");
        DashName.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DashName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DashNameMouseClicked(evt);
            }
        });

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/smallLogo.jpg"))); // NOI18N
        logo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logo.setIconTextGap(0);
        logo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoMouseClicked(evt);
            }
        });

        labelCashierName2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        labelCashierName2.setForeground(new java.awt.Color(255, 255, 255));
        labelCashierName2.setText("| CASHIER");

        btnLogout.setBackground(new java.awt.Color(255, 255, 0));
        btnLogout.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(25, 118, 211));
        btnLogout.setText("LOGOUT");
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.setFocusable(false);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        labelCashierName.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        labelCashierName.setForeground(new java.awt.Color(255, 255, 255));
        labelCashierName.setText("CASHIER");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(logo)
                .addGap(35, 35, 35)
                .addComponent(DashName, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelCashierName)
                .addGap(39, 39, 39)
                .addComponent(labelCashierName2)
                .addGap(29, 29, 29)
                .addComponent(btnLogout)
                .addGap(50, 50, 50))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logo)
                .addGap(65, 65, 65))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DashName)
                    .addComponent(labelCashierName2)
                    .addComponent(btnLogout)
                    .addComponent(labelCashierName))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(25, 118, 211));

        Order.setBackground(new java.awt.Color(25, 118, 211));
        Order.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Order.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OrderMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                OrderMousePressed(evt);
            }
        });

        ordersLabel.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        ordersLabel.setForeground(new java.awt.Color(255, 255, 255));
        ordersLabel.setText("ORDERS");

        javax.swing.GroupLayout OrderLayout = new javax.swing.GroupLayout(Order);
        Order.setLayout(OrderLayout);
        OrderLayout.setHorizontalGroup(
            OrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OrderLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(ordersLabel)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        OrderLayout.setVerticalGroup(
            OrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OrderLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(ordersLabel)
                .addGap(18, 18, 18))
        );

        Customer.setBackground(new java.awt.Color(25, 118, 211));
        Customer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Customer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CustomerMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CustomerMousePressed(evt);
            }
        });

        customerLabel.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        customerLabel.setForeground(new java.awt.Color(255, 255, 255));
        customerLabel.setText("CUSTOMERS");
        customerLabel.setToolTipText("");
        customerLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customerLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout CustomerLayout = new javax.swing.GroupLayout(Customer);
        Customer.setLayout(CustomerLayout);
        CustomerLayout.setHorizontalGroup(
            CustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CustomerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(customerLabel)
                .addGap(26, 26, 26))
        );
        CustomerLayout.setVerticalGroup(
            CustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CustomerLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(customerLabel)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(Order, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Customer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(Order, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(Customer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(591, Short.MAX_VALUE))
        );

        mainPane.setBackground(new java.awt.Color(255, 255, 255));
        mainPane.setPreferredSize(new java.awt.Dimension(1100, 491));

        javax.swing.GroupLayout mainPaneLayout = new javax.swing.GroupLayout(mainPane);
        mainPane.setLayout(mainPaneLayout);
        mainPaneLayout.setHorizontalGroup(
            mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 886, Short.MAX_VALUE)
        );
        mainPaneLayout.setVerticalGroup(
            mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(mainPane, javax.swing.GroupLayout.PREFERRED_SIZE, 886, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mainPane, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(774, 774, 774)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OrderMouseClicked
        // TODO add your handling code here:
        CashierOrderPanel CashierOrder = new CashierOrderPanel();
        mainPane.removeAll();
        mainPane.add(CashierOrder).setVisible(true);
    }//GEN-LAST:event_OrderMouseClicked

    private void OrderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OrderMousePressed
        // TODO add your handling code here:
        Order.setBackground(ClickedColor);
        Customer.setBackground(DefaultColor);

        ordersLabel.setForeground(Color.BLACK);
        customerLabel.setForeground(Color.WHITE);

    }//GEN-LAST:event_OrderMousePressed

    private void CustomerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CustomerMousePressed
        // TODO add your handling code here:

        Customer.setBackground(ClickedColor);
        Order.setBackground(DefaultColor);

        customerLabel.setForeground(Color.BLACK);
        ordersLabel.setForeground(Color.WHITE);

    }//GEN-LAST:event_CustomerMousePressed

    private void CustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CustomerMouseClicked
        // TODO add your handling code here:
        CashierCustomerPanel CashierCustomer = new CashierCustomerPanel();
        mainPane.removeAll();
        mainPane.add(CashierCustomer).setVisible(true);
    }//GEN-LAST:event_CustomerMouseClicked

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        int answer = JOptionPane.showConfirmDialog(null, "Are you sure you want to logout?", "Logout", JOptionPane.YES_NO_OPTION);

        if (answer == 0) {
            this.dispose();
            new Login();
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void logoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoMouseClicked
        // TODO add your handling code here:
        CashierDashboardPanel dashboardPanel = new CashierDashboardPanel();

        Customer.setBackground(DefaultColor);
        Order.setBackground(DefaultColor);

        customerLabel.setForeground(Color.WHITE);
        ordersLabel.setForeground(Color.WHITE);

        mainPane.removeAll();
        mainPane.add(dashboardPanel).setVisible(true);

    }//GEN-LAST:event_logoMouseClicked

    private void DashNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashNameMouseClicked
        // TODO add your handling code here:
        CashierDashboardPanel dashboardPanel = new CashierDashboardPanel();

        Customer.setBackground(DefaultColor);
        Order.setBackground(DefaultColor);

        customerLabel.setForeground(Color.WHITE);
        ordersLabel.setForeground(Color.WHITE);

        mainPane.removeAll();
        mainPane.add(dashboardPanel).setVisible(true);
    }//GEN-LAST:event_DashNameMouseClicked

    private void customerLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerLabelMouseClicked
        // TODO add your handling code here:
        Customer.setBackground(ClickedColor);
        Order.setBackground(DefaultColor);

        customerLabel.setForeground(Color.BLACK);
        ordersLabel.setForeground(Color.WHITE);
        
        CashierCustomerPanel CashierCustomer = new CashierCustomerPanel();
        mainPane.removeAll();
        mainPane.add(CashierCustomer).setVisible(true);
    }//GEN-LAST:event_customerLabelMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JPanel Customer;
    private javax.swing.JLabel DashName;
    public static javax.swing.JPanel Order;
    private javax.swing.JButton btnLogout;
    public static javax.swing.JLabel customerLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel labelCashierName;
    private javax.swing.JLabel labelCashierName2;
    private javax.swing.JLabel logo;
    public static javax.swing.JDesktopPane mainPane;
    public static javax.swing.JLabel ordersLabel;
    // End of variables declaration//GEN-END:variables
}
