/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Anaclita
 */
public class ManagerDashboard extends javax.swing.JFrame {

    /**
     * Creates new form AdminDashboard
     */
    Color DefaultColor,ClickedColor;
    
    
    
    public ManagerDashboard(String name) {
        initComponents();
        labelManagerName.setText(name);
        mainPane.add(new AdminDashboardPanel()).setVisible(true);
        
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        
        DefaultColor=new Color(25,118,211);
        ClickedColor=new Color (255,255,255);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        DashName = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        labelManagerName = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        labelManagerName1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Cashier = new javax.swing.JPanel();
        cashierLabel = new javax.swing.JLabel();
        Manager = new javax.swing.JPanel();
        managerLabel = new javax.swing.JLabel();
        Manager1 = new javax.swing.JPanel();
        managerLabel1 = new javax.swing.JLabel();
        mainPane = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(25, 118, 211));

        DashName.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        DashName.setForeground(new java.awt.Color(255, 255, 255));
        DashName.setText("Nackingspol Water Refilling Station");
        DashName.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DashName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DashNameMouseClicked(evt);
            }
        });

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/smallLogo.jpg"))); // NOI18N
        logo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logo.setIconTextGap(0);
        logo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoMouseClicked(evt);
            }
        });

        labelManagerName.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        labelManagerName.setForeground(new java.awt.Color(255, 255, 255));
        labelManagerName.setText("MANAGER");

        btnLogout.setBackground(new java.awt.Color(255, 255, 0));
        btnLogout.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(25, 118, 211));
        btnLogout.setText("LOGOUT");
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.setFocusable(false);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        labelManagerName1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        labelManagerName1.setForeground(new java.awt.Color(255, 255, 255));
        labelManagerName1.setText("MANAGER");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(logo)
                .addGap(35, 35, 35)
                .addComponent(DashName, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelManagerName1)
                .addGap(18, 18, 18)
                .addComponent(labelManagerName)
                .addGap(29, 29, 29)
                .addComponent(btnLogout)
                .addGap(50, 50, 50))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logo)
                .addGap(65, 65, 65))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DashName)
                    .addComponent(labelManagerName)
                    .addComponent(btnLogout)
                    .addComponent(labelManagerName1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(25, 118, 211));

        Cashier.setBackground(new java.awt.Color(25, 118, 211));
        Cashier.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Cashier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CashierMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CashierMousePressed(evt);
            }
        });

        cashierLabel.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        cashierLabel.setForeground(new java.awt.Color(255, 255, 255));
        cashierLabel.setText("ORDERS");

        javax.swing.GroupLayout CashierLayout = new javax.swing.GroupLayout(Cashier);
        Cashier.setLayout(CashierLayout);
        CashierLayout.setHorizontalGroup(
            CashierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CashierLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(cashierLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CashierLayout.setVerticalGroup(
            CashierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CashierLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(cashierLabel)
                .addGap(18, 18, 18))
        );

        Manager.setBackground(new java.awt.Color(25, 118, 211));
        Manager.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Manager.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ManagerMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ManagerMousePressed(evt);
            }
        });

        managerLabel.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        managerLabel.setForeground(new java.awt.Color(255, 255, 255));
        managerLabel.setText("CUSTOMER");

        javax.swing.GroupLayout ManagerLayout = new javax.swing.GroupLayout(Manager);
        Manager.setLayout(ManagerLayout);
        ManagerLayout.setHorizontalGroup(
            ManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManagerLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(managerLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ManagerLayout.setVerticalGroup(
            ManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManagerLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(managerLabel)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        Manager1.setBackground(new java.awt.Color(25, 118, 211));
        Manager1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Manager1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Manager1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Manager1MousePressed(evt);
            }
        });

        managerLabel1.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        managerLabel1.setForeground(new java.awt.Color(255, 255, 255));
        managerLabel1.setText("PRODUCTS");

        javax.swing.GroupLayout Manager1Layout = new javax.swing.GroupLayout(Manager1);
        Manager1.setLayout(Manager1Layout);
        Manager1Layout.setHorizontalGroup(
            Manager1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Manager1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(managerLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Manager1Layout.setVerticalGroup(
            Manager1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Manager1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(managerLabel1)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(Cashier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Manager, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Manager1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(Cashier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Manager, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(Manager1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(514, Short.MAX_VALUE))
        );

        mainPane.setBackground(new java.awt.Color(255, 255, 255));
        mainPane.setPreferredSize(new java.awt.Dimension(1100, 491));

        javax.swing.GroupLayout mainPaneLayout = new javax.swing.GroupLayout(mainPane);
        mainPane.setLayout(mainPaneLayout);
        mainPaneLayout.setHorizontalGroup(
            mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 886, Short.MAX_VALUE)
        );
        mainPaneLayout.setVerticalGroup(
            mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(mainPane, javax.swing.GroupLayout.PREFERRED_SIZE, 886, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mainPane, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(774, 774, 774)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CashierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CashierMouseClicked
        // TODO add your handling code here:
        AdminCashierPanel Cashier = new AdminCashierPanel();
        mainPane.removeAll();
        mainPane.add(Cashier).setVisible(true);
    }//GEN-LAST:event_CashierMouseClicked

    private void CashierMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CashierMousePressed
        // TODO add your handling code here:
        Cashier.setBackground(ClickedColor);
        Manager.setBackground(DefaultColor);
        
        cashierLabel.setForeground(Color.BLACK);
        managerLabel.setForeground(Color.WHITE);
        
    }//GEN-LAST:event_CashierMousePressed

    private void ManagerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManagerMousePressed
        // TODO add your handling code here:
       
        Manager.setBackground(ClickedColor);
        Cashier.setBackground(DefaultColor);
        
        managerLabel.setForeground(Color.BLACK);
        cashierLabel.setForeground(Color.WHITE);
        
    }//GEN-LAST:event_ManagerMousePressed

    private void ManagerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManagerMouseClicked
        // TODO add your handling code here:
        ManagerCustomerPanel ManagerCustomer = new ManagerCustomerPanel();
        mainPane.removeAll();
        mainPane.add(ManagerCustomer).setVisible(true);
    }//GEN-LAST:event_ManagerMouseClicked

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        int answer = JOptionPane.showConfirmDialog(null, "Are you sure you want to logout?", "Logout", JOptionPane.YES_NO_OPTION);
        
        if (answer == 0) {
            this.dispose();
            new Login();
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void logoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoMouseClicked
        // TODO add your handling code here:
        AdminDashboardPanel dashboardPanel = new AdminDashboardPanel();
        
        Manager.setBackground(DefaultColor);
        Cashier.setBackground(DefaultColor);
        
        managerLabel.setForeground(Color.WHITE);
        cashierLabel.setForeground(Color.WHITE);
        
        
        mainPane.removeAll();
        mainPane.add(dashboardPanel).setVisible(true);
        
    }//GEN-LAST:event_logoMouseClicked

    private void DashNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashNameMouseClicked
        // TODO add your handling code here:
        AdminDashboardPanel dashboardPanel = new AdminDashboardPanel();
        
        Manager.setBackground(DefaultColor);
        Cashier.setBackground(DefaultColor);
        
        managerLabel.setForeground(Color.WHITE);
        cashierLabel.setForeground(Color.WHITE);
        
        mainPane.removeAll();
        mainPane.add(dashboardPanel).setVisible(true);
    }//GEN-LAST:event_DashNameMouseClicked

    private void Manager1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Manager1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Manager1MouseClicked

    private void Manager1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Manager1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Manager1MousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JPanel Cashier;
    private javax.swing.JLabel DashName;
    public static javax.swing.JPanel Manager;
    public static javax.swing.JPanel Manager1;
    private javax.swing.JButton btnLogout;
    public static javax.swing.JLabel cashierLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel labelManagerName;
    private javax.swing.JLabel labelManagerName1;
    private javax.swing.JLabel logo;
    public static javax.swing.JDesktopPane mainPane;
    public static javax.swing.JLabel managerLabel;
    public static javax.swing.JLabel managerLabel1;
    // End of variables declaration//GEN-END:variables
}
