/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package views;

import javax.swing.plaf.basic.BasicInternalFrameUI;
import java.sql.*;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Anaclita
 */
public class ManagerTransactionPanel extends javax.swing.JInternalFrame {

    Statement stmt = null;
    ResultSet rs = null;
    PreparedStatement pstmt = null;

    public static HashMap<String, Integer> cashierMap = new HashMap<>();

    /**
     * Creates new form TableCashier
     */
    public ManagerTransactionPanel() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);

        getTransactionsFromDB();
    }

    public void getTransactionsFromDB() {
        try {
            stmt = DBConnect.getInstance().createStatement();

            String sql = "SELECT CONCAT(customer.FirstName, ' ', customer.Lastname) AS 'CustomerName', \n"
                    + "CONCAT(`user`.FirstName, ' ', `user`.LastName) AS 'CashierName', \n"
                    + "CONCAT(ContainerType, ' ', WaterType) AS 'Product', Quantity, Total, TypeOfTransaction,\n"
                    + "DATE_FORMAT(DateOfTransaction, '%M %e, %Y') AS 'DateOfTransaction' FROM transactions\n"
                    + "INNER JOIN customer ON transactions.CustomerID = customer.CustomerID\n"
                    + "INNER JOIN `user` ON transactions.CashierID = `user`.UserID\n"
                    + "INNER JOIN product ON transactions.ProductID = product.ProductID";
            rs = stmt.executeQuery(sql);

            while (rs.next()) {
                String customerName = rs.getString("CustomerName");
                String cashierName = rs.getString("CashierName");
                String product = rs.getString("Product");
                String quantity = String.valueOf(rs.getInt("Quantity"));
                String total = "Php " + String.valueOf(rs.getFloat("Total")) + "0";
                String typeOfTransaction = rs.getString("TypeOfTransaction");
                String dateOfTransaction = rs.getString("DateOfTransaction");

                String[] data = {customerName, cashierName, product, quantity, total, typeOfTransaction, dateOfTransaction};

                DefaultTableModel tblModel = (DefaultTableModel) tblTransaction.getModel();
                tblModel.addRow(data);
            }

            rs.close();
            stmt.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAddCashier = new javax.swing.JButton();
        btnEditCashier = new javax.swing.JButton();
        btnDeleteOrder = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTransaction = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setVisible(true);

        btnAddCashier.setBackground(new java.awt.Color(0, 153, 0));
        btnAddCashier.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnAddCashier.setForeground(new java.awt.Color(255, 255, 255));
        btnAddCashier.setText("ADD TRANSACTION");
        btnAddCashier.setFocusable(false);
        btnAddCashier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCashierActionPerformed(evt);
            }
        });

        btnEditCashier.setBackground(new java.awt.Color(255, 255, 0));
        btnEditCashier.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnEditCashier.setText("EDIT TRANSACTION");
        btnEditCashier.setFocusable(false);
        btnEditCashier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditCashierActionPerformed(evt);
            }
        });

        btnDeleteOrder.setBackground(new java.awt.Color(255, 0, 0));
        btnDeleteOrder.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnDeleteOrder.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteOrder.setText("DELETE TRANSACTION");
        btnDeleteOrder.setFocusable(false);
        btnDeleteOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteOrderActionPerformed(evt);
            }
        });

        tblTransaction.setAutoCreateRowSorter(true);
        tblTransaction.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        tblTransaction.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer Name", "Cashier Name", "Product", "Quantity", "Total", "Type of Transaction", "Date of Transaction"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTransaction.setMinimumSize(new java.awt.Dimension(50, 0));
        jScrollPane1.setViewportView(tblTransaction);
        if (tblTransaction.getColumnModel().getColumnCount() > 0) {
            tblTransaction.getColumnModel().getColumn(3).setMaxWidth(50);
            tblTransaction.getColumnModel().getColumn(4).setMaxWidth(100);
            tblTransaction.getColumnModel().getColumn(5).setMaxWidth(100);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddCashier)
                        .addGap(82, 82, 82)
                        .addComponent(btnEditCashier)
                        .addGap(79, 79, 79)
                        .addComponent(btnDeleteOrder))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 846, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(126, 126, 126))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddCashier)
                    .addComponent(btnEditCashier)
                    .addComponent(btnDeleteOrder))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddCashierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCashierActionPerformed
        // TODO add your handling code here:
        new AddTransactionDialog(null, true);
    }//GEN-LAST:event_btnAddCashierActionPerformed

    private void btnEditCashierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditCashierActionPerformed
        // TODO add your handling code here:

        DefaultTableModel tblModel = (DefaultTableModel) tblTransaction.getModel();

        if (tblTransaction.getSelectedRowCount() == 1) {
            String userName = tblModel.getValueAt(tblTransaction.getSelectedRow(), 2).toString();
            new EditCashierDialog(null, true, getCashierID(userName));
        } else {
            if (tblTransaction.getRowCount() == 0) {
                JOptionPane.showMessageDialog(null, "Table is empty!", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Please select a single row!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnEditCashierActionPerformed


    private void btnDeleteOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteOrderActionPerformed
        // TODO add your handling code here:

        if (tblTransaction.getSelectedRowCount() == 1) {

            DefaultTableModel tblModel = (DefaultTableModel) tblTransaction.getModel();

            String name = tblModel.getValueAt(tblTransaction.getSelectedRow(), 0).toString();
            int answer = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete " + name + "?", "Delete", JOptionPane.YES_NO_OPTION);

            if (answer == 0) {
                String userName = tblModel.getValueAt(tblTransaction.getSelectedRow(), 2).toString();

                int toDeleteID = getCashierID(userName);
                int deletedID = deleteCashierFromDB(toDeleteID);

                System.out.println(toDeleteID);
                if (deletedID > 0) {
                    tblModel.removeRow(tblTransaction.getSelectedRow());

                    JOptionPane.showMessageDialog(null, "Cashier deleted successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(null, "Cashier not deleted successfully!", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }

        } else {
            if (tblTransaction.getRowCount() == 0) {
                JOptionPane.showMessageDialog(null, "Table is empty!", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Please select a single row!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnDeleteOrderActionPerformed

    private int getCashierID(String userName) {
        int toDeleteID = 0;
        try {
            stmt = DBConnect.getInstance().createStatement();

            String sql = "SELECT UserID FROM user WHERE UserType = 'Cashier' AND Username = '" + userName + "'";
            rs = stmt.executeQuery(sql);

            rs.next();
            toDeleteID = rs.getInt("UserID");

            rs.close();
            stmt.close();
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }

        return toDeleteID;
    }

    private int deleteCashierFromDB(int deleteID) {
        int deletedRows = 0;
        try {
            String sql = "DELETE FROM user WHERE UserID = ?  AND UserType = 'Cashier'";

            pstmt = DBConnect.getInstance().prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);

            pstmt.setInt(1, deleteID);

            int rowAffected = pstmt.executeUpdate();
            deletedRows = rowAffected;

        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        } finally {
            try {
                if (rs != null) {
                    rs.close();
                }
            } catch (SQLException e) {
                System.out.println(e.getMessage());
            }
        }

        return deletedRows;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCashier;
    private javax.swing.JButton btnDeleteOrder;
    private javax.swing.JButton btnEditCashier;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tblTransaction;
    // End of variables declaration//GEN-END:variables
}
