/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package views;

import javax.swing.plaf.basic.BasicInternalFrameUI;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Anaclita
 */
public class TableCashier extends javax.swing.JInternalFrame {

    Statement stmt = null;
    ResultSet rs = null;
    PreparedStatement pstmt = null;
    
    /**
     * Creates new form TableCashier
     */
    public TableCashier() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui=(BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        
        getCashiersFromDB();
    }
    
    public void getCashiersFromDB() {
        try {
            stmt = DBConnect.getInstance().createStatement();
            
            String sql = "SELECT CONCAT(FirstName, ' ', LastName) AS Name, ContactNumber, Username, Password FROM user WHERE UserType = 'Cashier'";
            rs = stmt.executeQuery(sql);
            
            while (rs.next()) {
                String name = rs.getString("Name");
                String contactNumber = rs.getString("ContactNumber");
                String userName = rs.getString("Username");
                String password = rs.getString("Password");
                
                String [] data = {name, contactNumber, userName, password};
                
                DefaultTableModel tblModel = (DefaultTableModel) tblCashier.getModel();
                tblModel.addRow(data);
            }
            
            rs.close();
            stmt.close(); 
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAddCashier = new javax.swing.JButton();
        btnEditCashier = new javax.swing.JButton();
        btnDeleteCashier = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCashier = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        btnAddCashier.setBackground(new java.awt.Color(0, 153, 0));
        btnAddCashier.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnAddCashier.setForeground(new java.awt.Color(255, 255, 255));
        btnAddCashier.setText("ADD");
        btnAddCashier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCashierActionPerformed(evt);
            }
        });

        btnEditCashier.setBackground(new java.awt.Color(255, 255, 0));
        btnEditCashier.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnEditCashier.setText("EDIT");
        btnEditCashier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditCashierActionPerformed(evt);
            }
        });

        btnDeleteCashier.setBackground(new java.awt.Color(255, 0, 0));
        btnDeleteCashier.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnDeleteCashier.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteCashier.setText("DELETE");
        btnDeleteCashier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCashierActionPerformed(evt);
            }
        });

        tblCashier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Contact Number", "Username", "Password"
            }
        ));
        jScrollPane1.setViewportView(tblCashier);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAddCashier)
                        .addGap(74, 74, 74)
                        .addComponent(btnEditCashier)
                        .addGap(68, 68, 68)
                        .addComponent(btnDeleteCashier)
                        .addGap(70, 70, 70))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 966, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddCashier)
                    .addComponent(btnEditCashier)
                    .addComponent(btnDeleteCashier))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddCashierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCashierActionPerformed
        // TODO add your handling code here:
        new AddCashierDialog(null, true);
    }//GEN-LAST:event_btnAddCashierActionPerformed

    private void btnEditCashierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditCashierActionPerformed
        // TODO add your handling code here:
        new EditCashierDialog(null,true);
    }//GEN-LAST:event_btnEditCashierActionPerformed

    private void btnDeleteCashierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCashierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteCashierActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCashier;
    private javax.swing.JButton btnDeleteCashier;
    private javax.swing.JButton btnEditCashier;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCashier;
    // End of variables declaration//GEN-END:variables
}
